### ISSUE TITLE
Scraper la liste des PRADA

### ISSUE THREAD

**Issue by samgoeta** [okfnfr/dada-france-theme#14]
Scraper la liste des PRADA issues du site de la CADA https://www.cada.fr/administration/personnes-responsables

**Comment by samgoeta** [comment]
Fondements juridiques sur l'extraction de ces données personnelles : 
https://teamopendata.org/t/guide-commun-cnil-et-cada-open-data-rgpd/1320
https://teamopendata.org/t/decret-sur-les-documents-administratifs-pouvant-etre-rendus-publics-sans-faire-lobjet-dun-processus-danonymisation/963

**Comment by samgoeta** [comment]
Résultats du hackathon
- Avec [Web Scraper](https://webscraper.io), j'ai scrapé toutes les pages individuelles des administrations référencées sur [l'annuaire des PRADA](https://www.cada.fr/administration/personnes-responsables)
- Voici la configuration du scraper, elle peut être réimportée dans WebScraper directement : 
`{"_id":"prada4","startUrl":["https://datactivist.coop/scrap-prada/index_prada.html"],"selectors":[{"id":"type","type":"SelectorLink","parentSelectors":["_root"],"selector":"a","multiple":true,"delay":0},{"id":"pagination","type":"SelectorLink","parentSelectors":["type","pagination"],"selector":"li.pager-item:nth-of-type(n+2) a","multiple":true,"delay":0},{"id":"link","type":"SelectorLink","parentSelectors":["type","pagination"],"selector":".title a","multiple":true,"delay":0},{"id":"institution","type":"SelectorText","parentSelectors":["link"],"selector":"h1","multiple":true,"regex":"","delay":0},{"id":"pr-nom-prada","type":"SelectorText","parentSelectors":["link"],"selector":".field-name-field-pr-nom-prada div.field-item","multiple":true,"regex":"","delay":0},{"id":"adresse","type":"SelectorText","parentSelectors":["link"],"selector":".field-item p","multiple":true,"regex":"","delay":0}]}` 
- le scraper rencontre un bug pour extraire les noms des PRADA, je ne comprends parce que les éléments sont bien détectés : voici [les données](https://app.workbenchdata.com/public/moduledata/live/124795.csv)
- je parviens à scraper facilement les éléments des 5110 institutions référencées : https://app.workbenchdata.com/workflows/27305/ mais je suis limité par Workbench qui n'autorise que 10 pages web à la fois. Le lien précédent donne les Xpath des éléments suivants : nom institution,prénom NOM de la PRADA, adresse complète

**Comment by samgoeta** [comment]
Scraping en cours via Google Spreadsheet (oui je sais c'est pas libre mais ça fait la job rapidement) : https://docs.google.com/spreadsheets/d/1QrAsL6RUrAc_KmF-Sw1uwmc8Zus8XnAMZzzj6Iqiu9k/edit#gid=0

**Comment by pzwsk** [comment]
Salut Sam, tu aurais à minima la liste des PRADA et contact email pour les
ministères, autorités indépendantes, institutions et juridictions (une
centraine d'administration) ?

Cf https://github.com/okfnfr/dada-france-authorities

La plupart proposent un formulaire de contact à la place de l'email dans
l'annuaire de l'administration.

Quand c'était disponible, j'ai ajouté le contact email presse mais mieux si
on a directement l'email du PRADA.

Merci !

**Comment by samgoeta** [comment]
Aucun problème mais pour ça il me faudrait les noms de domaine, tu les as ?

**Comment by pzwsk** [comment]
Oui, il y a les urls des sites dans l'annuaire. À supposer que les noms de
domaine des emails sont similaires.
