### ISSUE TITLE
Build dev cassé

### ISSUE THREAD

**Issue by pzwsk** [okfnfr/dada-france-theme#20]
cc @laurentS 

voici le message d'erreur :

fatal: [dadastaging.okfn.fr]: FAILED! => {"changed": false, "msg": "'/usr/bin/apt-get upgrade --with-new-pkgs ' failed: E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. \n", "rc": 100, "stdout": "", "stdout_lines": []}

**Comment by laurentS** [comment]
@pzwsk je pense que c'est réparé, désolé pour le delai. Pas entierement sûr de ce qui posait problème, mais je soupçonne un peu de spaghetti dans les dépendances APT.

**Comment by pzwsk** [comment]
Ok merci, du coup je vois que le site lui même est cassé ...

Je vais regarder ça.

**Comment by laurentS** [comment]
d'après les logs du serveur, l'erreur est ici: https://github.com/okfnfr/dada-france-theme/blob/6682649393ce247b921b5ef302770e1d4cf435f4/lib/views/general/_responsive_header.html.erb#L9:
```
        <h1 style="font-weight: normal;"><%= link_to site_name, frontpage_path, :class => 'site-title__logo' % style="float: left;margin-right: 1em;">Ma demande d'accès à un document administratif</h1>
```
je pense que tu n'as pas correctement fermé le tag `<%` avec un `%>`
