### ISSUE TITLE
changer la destination du lien liste demandes page accueil

### ISSUE THREAD

**Issue by akakeronos** [okfnfr/dada-france-theme#37]
depuis la page d'accueil un lien liste le nombre de demandes en cours et permet de voir le détail.
Actuellement il pointe vers la liste des demandes abouties au lieu de la liste des demandes en cours

changer https://madada.fr/demandes/abouties par https://madada.fr/demandes/toutes

**Comment by pzwsk** [comment]
Ok je m'en occupe.

**Comment by akakeronos** [comment]
Le lien dans le menu du haut continue de pointer vers le sous-ensemble des demandes abouties. Je regarde si je trouve àù corriger et en attendant je re-ouvre cette issue

**Comment by akakeronos** [comment]
ce comportement est le comportement par défaut d'alaveteli. Est-ce qu'on le modifie en attendant d'avoir plus de demandes ? Faut-il dans le cas contraire expliciter le lien : parcourir les demandes abouties (ou fructueuses?)

**Comment by akakeronos** [comment]
Ce lien est configuré dans un fichier nav_items.rb qui n'a pas été surchargé dans le dépôt dada-france-theme

**Comment by pzwsk** [comment]
J'avais modifié bizarre ...

Je regarde

Le ven. 15 nov. 2019 à 12:27 PM, Pascal Romain <notifications@github.com> a
écrit :

**Comment by akakeronos** [comment]
C'est parce qu'il y a 2 liens qui conduisent à cette page : 
* un dans le menu
* un dans le corps de la page
