### ISSUE TITLE
Traduction/formattage sur la page d'une demande

### ISSUE THREAD

**Issue by laurentS** [okfnfr/dada-france-theme#39]
deux petits défauts de mise en forme :
* des bouts de texte en anglais "made this" et "request to"
* des espaces manquants autour de "en attente de réponse"

par exemple sur cette page https://madada.fr/demande/dotation_dequipement_des_territo#incoming-1

**Comment by laurentS** [comment]
a priori, c'est sur transifex que ça se passe, le challenge étant de trouver la bonne chaine de charactères. Il faudra peut être regarder dans le code pour trouver la bonne.

**Comment by akakeronos** [comment]
La première c'est la chaîne 1554 pour laquelle j'ai proposé une traduction
La seconde c'est la chaîne 384 mais apparemment il y a déjà les espaces autour de la chaîne traduite. J'ai proposé une nouvelle traduction

**Comment by laurentS** [comment]
@akakeronos la traduction de la chaine 384 que tu as proposée était sur la locale `fr`, mais on utilise `fr_FR`, donc j'ai recopié ta suggestion. Le resultat me semble correct sur le site, je ferme ce ticket.
