### ISSUE TITLE
Créer un design visuel + logo pour le site

### ISSUE THREAD

**Issue by laurentS** [okfnfr/dada-france-theme#4]
A minima: un jeu de couleurs et un logo

**Comment by laurentS** [comment]
https://travis-ci.org/okfnfr/dada-core pour reconstruire le site

**Comment by pzwsk** [comment]
Utiliser https://github.com/okfnfr/dada-france-theme/tree/staging

Puis https://travis-ci.org/okfnfr/dada-core

**Comment by pzwsk** [comment]
![image](https://user-images.githubusercontent.com/2378439/65836182-cca5f480-e2ef-11e9-9fab-2fd6bf84919f.png)

**Comment by pzwsk** [comment]
Quelques infos et questions

- Le design reprend le code couleur du site service-public.fr
- Le logo et le nom tranchent avec le design formel du site. On garde ou pas ?

**Comment by pzwsk** [comment]
@laurentS je n'arrive pas à trouver la frontpage qui devrait être dans lib/views/general/frontpage.html.erb

une idée ?

**Comment by laurentS** [comment]
> @laurentS je n'arrive pas à trouver la frontpage qui devrait être dans lib/views/general/frontpage.html.erb

Dans https://github.com/mysociety/alaveteli/tree/develop/app/views/general tu as une série de `fichier.html.erb` dont tu peux remplacer le contenu en copiant ceux que tu veux dans https://github.com/okfnfr/dada-france-theme/tree/master/lib/views/general en gardant le même nom. Tu modifies ensuite le fichier dans `dada-france-theme`, et tout ça devrait être mixé correctement lors du déploiement. Je pense que tu ne devrais pas avoir besoin de copier les fichiers inchangés.

**Comment by cecilaki** [comment]
Merci ça commence à avoir du souffle ce site ! Pour répondre à @pzwsk : 

> Le design reprend le code couleur du site service-public.fr
Pas complètement, le beige en plus. Mais sinon c'est vrai que ça donne un petit côté institutionnel qui me plait bien.

> Le logo tranche avec le design formel du site. On garde ou pas ?
Le petit âne.. bof c'est vrai. Ça infantilise le projet je trouve, c'est dommage, c'est hyper sérieux et utile.

**Comment by pzwsk** [comment]
Hello @laurentS besoin de ton aide.

Je ne vois plus la branche staging sur Travis ...

Par ailleurs, c'est vraiment pas l'idéal de travailler dans le noir, surtout vu la complexité du front.

Tu aurais pas un conseil pour que je puisse au moins faire tourner une version du site en local, au moins le front ? Dès que j'ai ça, il me faut 2h pour faire les modifs je pense.

Merci beaucoup

**Comment by laurentS** [comment]
@pzwsk je vois 2 options pour t'aider:
1. Installer alaveteli en local sur ta machine. C'est l'idéal, parce que tu vois les effets des changements en direct. Instructions [ici](https://alaveteli.org/docs/installing/vagrant/) ce n'est pas forcement le plus évident, mais ça doit marcher (je l'ai fait sur ma machine il y'a un moment). Une fois que tu as la base qui fonctionne, il te faut aussi rajouter le theme dada depuis https://github.com/okfnfr/dada-france-theme (branche `staging`) (sauf erreur, il faut que tu copies le repo sous `alaveteli/lib/themes/` pour avoir `alaveteli/lib/themes/dada-france-theme`). Je ne pense pas que copier la config depuis `dada-core` soit vraiment facile (il faudrait compiler les templates... et ça ne change pas vraiment le visuel, si je me souviens bien) mais tu devrais pouvoir récupérer les traductions depuis transifex avec leur client (voir [ce ticket](https://github.com/okfnfr/dada-france-theme/issues/3) pour un peu d'instructions, sinon tu récupères juste le fichier depuis [cette page](https://www.transifex.com/mysociety/alaveteli/language/fr_FR/) en cliquant sur `app.po` puis `download for use`, et tu copies ça sous `alaveteli/locale/fr_FR/`.
A ce stade, tu devrais pouvoir bosser en local, avec un site qui ressemble pour l'essentiel á madada.fr.
2. Utiliser dadastaging.okfn.fr pour tester. Dans ce cas, tu fais les changements en local, dans ta copie de https://github.com/okfnfr/dada-france-theme (branche `staging`), puis commit/push, et ensuite, tu dois pouvoir relancer le dernier build (branche `dev`) depuis [la page des builds travis](https://travis-ci.org/okfnfr/dada-core/builds). Beaucoup moins de setup ici, mais chaque test prendra 3-4 minutes.

**Comment by pzwsk** [comment]
Merci @laurentS mais je suis toujours confus pour l'option 2, si je fais un build depuis la branche `dev`, pourquoi faire un push dans la branche `staging` ?

**Comment by laurentS** [comment]
J'admets que c'est un peu déroutant. C'est parce qu'il y'a 2 repos:
- `dada-france-theme` sur lequel tu vas faire tes modifs HTML/CSS/etc... (branche 'staging')
- `dada-core` dans lequel il y'a la mécanique de déploiement. (branche `dev`)

Si tu fais un push sur le repo du theme, quelle que soit la branche, il ne se passera rien.

J'ai gardé 2 repos essentiellement pour suivre la structure d'alaveteli qui a séparé tout ça. Il doit être possible de grouper tout ça en un seul repo, mais je ne suis pas sûr des conséquences lors des mises à jour de version d'alaveteli.

**Comment by pzwsk** [comment]
Ah ok, merci pour l'explication.

Je viens de voir que ça fonctionne en fait https://dadastaging.okfn.fr/ et
que j'ai encore du boulot ;)

**Comment by pzwsk** [comment]
Bon j'y suis presque https://dadastaging.okfn.fr/

Questions pour toi @laurentS :

1. La traduction est déployée automatiquement sur la production lors d'un nouveau build mais pas sur la version dev, n'est ce pas ?

2. Je trouve pas le fichier de config avec le nom du site

Merci

**Comment by laurentS** [comment]
1. Je ne vois pas de différences évidentes, a priori, les deux serveurs doivent marcher exactement de la même façon. Est-ce que tu as un exemple précis? Ça m'aiderait à trouver le problème
2. si tu parles du `<% site_name %>` je crois qu'il est dans `dada-core` ici `ansible/roles/alaveteli/templates/config_general.yml:SITE_NAME: 'DadaFrance'`
