### ISSUE TITLE
reformulation d'emails

### ISSUE THREAD

**Issue by akakeronos** [okfnfr/dada-france-theme#41]
* [ ] Fwd: N'oubliez pas de mettre à jour le statut de votre demande
* [ ] Fwd: Vous attendez depuis longtemps une réponse à votre demande d'accès à l'information - Holding pen

**Comment by akakeronos** [comment]
@laurentS je t'ai envoyé par mail 2 propositions à discuter

**Comment by laurentS** [comment]
J'ai mis à jour les traductions (le texte est sur transifex), mais les templates de mails sont assez complexes, donc il faudra garder un oeil sur les mails reçus pour valider leur contenu. C'est pour l'instant déployé sur le serveur de test uniquement

**Comment by pzwsk** [comment]
Poster les textes ici.

**Comment by laurentS** [comment]
je ferme ce ticket, on en a d'autres plus précis et à jour...
