### ISSUE TITLE
Travis - Bouton Re-build branch a disparu

### ISSUE THREAD

**Issue by pzwsk** [okfnfr/dada-france-theme#57]
![image](https://user-images.githubusercontent.com/2378439/68531504-10d6dc80-0313-11ea-892d-33b0f7a82c4c.png)

**Comment by laurentS** [comment]
J'ai eu ce probleme il y'a quelques jours, je pense que c'est un bug de travis. Ca s'est reglé après un logout/login, et je crois un redémarrage de navigateur (ou peut être plus simplement purge du cache).

**Comment by pzwsk** [comment]
Merci, effectivement le bouton est réapparu après un simple log out / log in.
