### ISSUE TITLE
Trouver et réserver un nom de domaine

### ISSUE THREAD

**Issue by laurentS** [okfnfr/dada-france-theme#6]
idées bienvenues!

**Comment by laurentS** [comment]
2 propositions (les 2 domaines sont dispos)
- opendada.fr
- dadafrance.fr

dada.fr est déjà pris :(

**Comment by samgoeta** [comment]
opendada.fr c'est juste génial <3

**Comment by samgoeta** [comment]
Décision à l'issue du hackathon : madada.fr 

@laurentS le nom de domaine est réservé ?

**Comment by samgoeta** [comment]
Mais ça marche, super ! https://madada.fr/
