### ISSUE TITLE
Que veut dire "reconsidération" ?

### ISSUE THREAD

**Issue by oncletom** [okfnfr/dada-france-theme#71]
Qu'est-ce que veut dire le terme "Reconsidération" ? Qui reconsidère ?

J'ai ce terme qui apparaît quand on me demande de "relancer" une autorité.

**Comment by laurentS** [comment]
Je pense que #70 devrait répondre à ta question. On est en train de corriger ça.

**Comment by oncletom** [comment]
En effet, bien vu ! Merci @laurentS.
