### ISSUE TITLE
chaine de caractère non traduite "they are going to reply by post"

### ISSUE THREAD

**Issue by akakeronos** [okfnfr/dada-france-theme#72]
Si ma demande n'a pas été acceptée je peux mettre à jour son statut.
Cela m'amène sur une page https//madada.fr/:id/update_status=1

La troisième chaîne de caractère n'est pas traduite

**Comment by laurentS** [comment]
C'est reglé, après une mise à jour d'alaveteli vers 0.33.0.0

**Comment by laurentS** [comment]
Après discussion avec mySociety, la chaine n'apparait pas dans transifex parce qu'elle a disparu entre la version qu'on utilise et la plus récente. Transifex ne garde malheureusement que les chaines de charactères de la version du logiciel la plus récente.
Le plus logique serait de mettre à jour notre version d'alaveteli :)
