### ISSUE TITLE
Lister les partenaires potentiels

### ISSUE THREAD

**Issue by samgoeta** [okfnfr/dada-france-theme#9]
- [x] - OK France Membres ~~(ajouter Laurent / c'est fait)~~
- [x] - Regards Citoyens
- [x] - Code for France
- [x] - Ouvre-Boite.org
- [x] - Next Inpact
- [x] - Bureau ouvert (Cabinet Paula Forteza)
- [ ] - SavoirsComm1
- [ ] - Transparency France
- [ ] - Anticor
- [ ] - Framasoft

A l'international : 
- [ ] réseau international FOIAnet (en anglais)
- [x] Access Info (http://asktheeu.org/)
- [ ] Article 19

**Comment by samgoeta** [comment]
J'ai rajouté quelques acteurs internationaux + Code for France

**Comment by laurentS** [comment]
+ http://asktheeu.org/  qui se focalise sur les instances EU, ils ont une version française du site

**Comment by samgoeta** [comment]
AsktheU, c'est Access Info. 

Il faudrait aussi rajouter : 
- SavoirsComm1 
- Transparency France
- Anticor
- Framasoft

**Comment by samgoeta** [comment]
Open law aussi

**Comment by laurentS** [comment]
Transparencia.be
