### ISSUE TITLE
Mise à jour des PRADA

### ISSUE THREAD

**Issue by pzwsk** [okfnfr/dada-france-theme#90]
Question de compétence : des PRADA compétentes pour plusieurs ministères, plusieurs services ou plusieurs collectivités. Une PRADA pour les ministères sociaux. 
Intérêt de passer par les PRADA. 
On relance celles qui ne le font pas. 
Pas de mise à jour depuis un an des PRADA : mis à jour régulièrement. Cas des ministères qui fusionnent ou changent de périmètre : mettre à jour régulièrement. 
On privilégie les adresses fonctionnelles, on les incite à utiliser cette adresse.

**Comment by samgoeta** [comment]
En faisant une comparaison entre la version du fichier des PRADA que nous avons importé et celle qui est actuellement [en ligne](https://www.cada.fr/lacada/annuaire-des-prada), je n'ai trouvé que 3 différences : 2 ajouts et une modification 
![Capture d’écran 2020-07-28 à 15 32 46](https://user-images.githubusercontent.com/2378397/88676073-f1bfeb00-d0eb-11ea-88c0-8f22a48ba0f8.png)

**Comment by samgoeta** [comment]
J'ai fait une différence entre le fichier des PRADA importé au lancement du site et celui en ligne sur le [site de la CADA](https://www.cada.fr/lacada/annuaire-des-prada), voici les ajouts : 

- 14        Communauté de communes de l'estuaire de la Dives        Jérôme        LE TENSORER        cada@cc-estuairedeladives.fr        Monsieur le président de la communauté de communes de l'estuaire de la Dives Direction générale des services - A l'attention de Monsieur Jérôme LE TENSORER Rue de la Vignerie        14165 / DIVES-SUR-MER CEDEX

--> n'existe plus (cf https://fr.wikipedia.org/wiki/Communaut%C3%A9_de_communes_de_l%27Estuaire_de_la_Dives), c'est désormais la communauté de communes Normandie-Cabourg-Pays d'Auge qui existe sur madada.fr :  https://madada.fr/body/communaute_de_communes_normandie_cabourg_pays_dauge

- 62        Communauté d'agglomération de l'Artois        Jean-Louis        ADANCOURT        contact@agglo-artoiscomm.fr        Monsieur le président de la communauté d'agglomération de l'Artois A l'attention de Monsieur Jean-Louis ADANCOURT Hôtel Communautaire - 100 avenue de Londres - BP 548        62411 / BETHUNE CEDEX

--> n'existe plus, c'est désormais la communauté d'agglomération de Béthune-Bruay, Artois-Lys Romane qui figure sur madada.fr : https://madada.fr/body/communaute_dagglomeration_bethune_bruay_artois_lys_romane

- 92        Mairie de Villeneuve-la-Garenne        Virginie        MICHEL        vmichel@villeneuve92.com        Monsieur le maire Hôtel de Ville - BP 30 Service archives-patrimoine - A l'attention de Madame Virginie MICHEL        92391 / VILLENEUVE-LA-GARENNE CEDEX
 --> https://madada.fr/body/mairie_villeneuve_la_garenne : adresse ok sur madada.fr
