### ISSUE TITLE
modifier courrier type demande

### ISSUE THREAD

**Issue by akakeronos** [okfnfr/dada-france-theme#99]
1. ajouter mention CRPA

* Comme le livre III du code des relations entre le public et l’administration le prévoit lorsque le demandeur a mal identifié celui qui est susceptible de répondre à sa requête, je vous prie de bien vouloir transmettre ma demande au service qui détient les documents demandés si tel est le cas

2 ajouter mentions CADA

Je souhaite recevoir ces documents dans un format numérique, ouvert et réutilisable. Pour ce faire, veuillez m’indiquer leur adresse de téléchargement ou me les envoyer en pièce jointe.
Veuillez agréer, Monsieur, l'expression de mes sentiments distingués. 

* En application de la loi n° 78-575 du 17 juillet 1978 relative aux documents administratifs, je souhaiterai recevoir communication de ces documents administratifs :

**Comment by laurentS** [comment]
Pas trivial de retrouver où ces modifications se font:
- pour la demande "non pro", le texte est dans transifex, sous la clé `Dear {{public_body_name}},`, utilisée dans le fichier `app/models/outgoing_message/template/initial_request.rb`
- pour la demande pro, le texte est sous la clé `Dear [Authority name],` qui va dans le fichier `app/models/outgoing_message/template/batch_request.rb`

Attention, il y'a plusieurs parties de texte, voir le détail dans les fichiers templates.

**Comment by akakeronos** [comment]
J'ai mis à jour les traductions dans transiflex pour les 2 versions.

* pour la version courante j'ai ajouté la mention à l'obligation de donner suite en cas de mauvais destinataire
* pour la version pro j'ai ajouté à la chaîne Dear [Authority Name] les 3 chaînes de caractère du modèle

Je n'ai pas vu les différentes parties de texte dans les fichiers templates

**Comment by pzwsk** [comment]
Merci à vous deux, c'est bon pour moi. Je propose de fermer cette issue.

**Comment by akakeronos** [comment]
En side effect la chaîne Dear [Autority Name] est également utilisée dans le formulaire de courrier de réponse utilisé lors d'une demande d'ajout d'autorité publique.
